title: IndicaAi
description: Compartilhe com a gente os locais que vocÃª gosta de ir no tempo livre da FGA.
author: Indica Ai
logo: /assets/logo.png
github: https://github.com/fga-eps-mds/2018.2-IndicaAi
about: 2018 EPS / MDS

baseurl: ""
#baseurl: "https://fga-eps-mds.github.io/2018.2-IndicaAi/"
url: "https://fga-eps-mds.github.io/2018.2-IndicaAi/"

allowsearch: true

# disqus_shortname: aboutashu
# google_analytics: UA-72862926-1

# share:
  # twitter_username: \#
  # fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
